id = "svelte"
name = "Svelte"
description = "Svelte support"
version = "0.2.11"
schema_version = 1
authors = ["Zed Industries <support@zed.dev>"]
repository = "https://github.com/zed-extensions/svelte"

[language_servers.svelte-language-server]
name = "Svelte Language Server"
language = "Svelte"

[grammars.svelte]
repository = "https://github.com/themixednuts/tree-sitter-htmlx"
commit = "9733eb68e29a9ade89eb7fade6866d3a22d50750"
path = "crates/tree-sitter-svelte"
