id = "svelte"
name = "Svelte"
description = "Svelte support"
version = "0.2.11"
schema_version = 1
authors = ["Zed Industries <support@zed.dev>"]
repository = "https://github.com/zed-extensions/svelte"

[language_servers.svelte-language-server]
name = "Svelte Language Server"
language = "Svelte"

[grammars.svelte]
repository = "https://github.com/themixednuts/tree-sitter-htmlx"
commit = "c6a366163fb7b4633285853c919c1b7f03ee40e0"
path = "crates/tree-sitter-svelte"
